use spotify_project;
create table track_detail(
  track_id   varchar(200),     
   track_name    varchar(200) ,       
artist_name     text  ,     
    released_year   year,               
   popularity       int  ,   
    artwork_url    varchar(200),       
    album_name     varchar(200),        
    acousticness      float, 
    danceability   float , 
    duration_ms     float  ,  
   energy      float   , 
   instrumentalness  float,  
   track_key      float ,          
   liveness      float ,      
   loudness    float  ,   
   track_mode  float  ,           
   speechiness   float  ,  
   tempo         float ,
   time_signature float ,    
   valence      float   , 
   track_url     varchar(200) ,    
   track_language  varchar(200) ,     
   duration_minutes float ) ;